# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da778a80eeb20f7f5576700298f987b7174ee859d21fdfb8e76a61ac95e31d34ae7b82891a081383cd5c1fcd19b934e2ecaf7947f7e3313a3c96fa54594e96a2

test:
  secret_key_base: 605b13592a0fc49996fb1b7eef4fa46540fbe644fe9e2b4f4893c43f047859ba9e41c5ca1abc0af014b2d9d1c9df9469525f363195863e7bd297f01e83b4a800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
